services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: todo_user
      POSTGRESQL_PASSWORD: todo_password
      POSTGRESQL_DATABASE: todo_db
      POSTGRESQL_POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
